// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mlik/internal/service/internal/dao/internal"
)

// internalSubscriptionsDao is internal type for wrapping internal DAO implements.
type internalSubscriptionsDao = *internal.SubscriptionsDao

// subscriptionsDao is the data access object for table subscriptions.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionsDao struct {
	internalSubscriptionsDao
}

var (
	// Subscriptions is globally public accessible object for table subscriptions operations.
	Subscriptions = subscriptionsDao{
		internal.NewSubscriptionsDao(),
	}
)

// Fill with you ideas below.
