// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mlik/internal/service/internal/dao/internal"
)

// internalSubscriptionCallbacksDao is internal type for wrapping internal DAO implements.
type internalSubscriptionCallbacksDao = *internal.SubscriptionCallbacksDao

// subscriptionCallbacksDao is the data access object for table subscription_callbacks.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionCallbacksDao struct {
	internalSubscriptionCallbacksDao
}

var (
	// SubscriptionCallbacks is globally public accessible object for table subscription_callbacks operations.
	SubscriptionCallbacks = subscriptionCallbacksDao{
		internal.NewSubscriptionCallbacksDao(),
	}
)

// Fill with you ideas below.
