// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mlik/internal/service/internal/dao/internal"
)

// internalSubscriptionPeriodsDao is internal type for wrapping internal DAO implements.
type internalSubscriptionPeriodsDao = *internal.SubscriptionPeriodsDao

// subscriptionPeriodsDao is the data access object for table subscription_periods.
// You can define custom methods on it to extend its functionality as you wish.
type subscriptionPeriodsDao struct {
	internalSubscriptionPeriodsDao
}

var (
	// SubscriptionPeriods is globally public accessible object for table subscription_periods operations.
	SubscriptionPeriods = subscriptionPeriodsDao{
		internal.NewSubscriptionPeriodsDao(),
	}
)

// Fill with you ideas below.
