// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mlik/internal/service/internal/dao/internal"
)

// internalUsersDao is internal type for wrapping internal DAO implements.
type internalUsersDao = *internal.UsersDao

// usersDao is the data access object for table t_users.
// You can define custom methods on it to extend its functionality as you wish.
type usersDao struct {
	internalUsersDao
}

var (
	// Users is globally public accessible object for table t_users operations.
	Users = usersDao{
		internal.NewUsersDao(),
	}
)

// Fill with you ideas below.
