// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mlik/internal/service/internal/dao/internal"
)

// internalUserTagRelationsDao is internal type for wrapping internal DAO implements.
type internalUserTagRelationsDao = *internal.UserTagRelationsDao

// userTagRelationsDao is the data access object for table t_user_tag_relations.
// You can define custom methods on it to extend its functionality as you wish.
type userTagRelationsDao struct {
	internalUserTagRelationsDao
}

var (
	// UserTagRelations is globally public accessible object for table t_user_tag_relations operations.
	UserTagRelations = userTagRelationsDao{
		internal.NewUserTagRelationsDao(),
	}
)

// Fill with you ideas below.
