// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Subscriptions is the golang structure of table subscriptions for DAO operations like Where/Data.
type Subscriptions struct {
	g.Meta                `orm:"table:subscriptions, do:true"`
	Id                    interface{} // 主键ID
	SubscriptionNo        interface{} // 订阅单号
	Uid                   interface{} // 用户ID
	Sku                   interface{} // 商品ID
	IsSandbox             interface{} // 是否是沙盒环境
	App                   interface{} // 平台app名称
	Package               interface{} // app包名称
	Channel               interface{} // 支付渠道
	PayConfig             interface{} // 生成时的支付配置信息
	SubscriptionId        interface{} // 订阅ID
	Amount                interface{} // 订单金额
	PurchaseToken         interface{} // 用户订阅的最新的token
	Subject               interface{} // 商品标题
	Body                  interface{} // 商品描述
	Extra                 interface{} // json支付额外数据
	OriginalTransactionId interface{} // 第三方原始交易号
	Credential            interface{} // json交易凭证
	Version               interface{} // 订阅时app版本号
	Currency              interface{} //
	SubscriptionPeriod    interface{} // 订阅周期（单位：天）
	Status                interface{} // 状态 -1: 已过期； 0 待付款； 1 - 订阅中； 2 - 订阅已失效； 3 - 订阅已暂停； 4 - 订阅已撤销；
	CreatedBy             interface{} // 创建资源的用户标识
	CallbackUri           interface{} // 回调地址
	CallbackResult        interface{} // 回调结果
	Remark                interface{} // 备注
	PayAccount            interface{} // 支付账号
	Meta                  interface{} // json自定义元数据
	ExpiredAt             *gtime.Time // 过期时间
	RefundedAt            *gtime.Time // 退款时间
	ReversedAt            *gtime.Time // 撤销时间
	CreatedAt             *gtime.Time // 创建时间
	UpdatedAt             *gtime.Time // 更新时间
	DeletedAt             *gtime.Time // 删除时间
	StartedAt             *gtime.Time // 订阅开始时间
	EndedAt               *gtime.Time // 订阅到期时间
}
