// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SubscriptionCallbacks is the golang structure of table subscription_callbacks for DAO operations like Where/Data.
type SubscriptionCallbacks struct {
	g.Meta                `orm:"table:subscription_callbacks, do:true"`
	Id                    interface{} // 主键ID
	App                   interface{} // 应用标识
	SubscriptionNo        interface{} // 订阅单号
	Channel               interface{} // 支付渠道
	OriginalTransactionId interface{} // 第三方原始交易号
	TransactionNo         interface{} // 第三方交易号
	Type                  interface{} // 回调类型1=第三方回调2=内部回调
	Status                interface{} // 当前回调的订阅状态
	Data                  interface{} // json回调数据
	Result                interface{} // 回调结果
	CreatedAt             *gtime.Time // 创建时间
	UpdatedAt             *gtime.Time // 更新时间
	DeletedAt             *gtime.Time // 删除时间
}
