// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TTags is the golang structure of table t_tags for DAO operations like Where/Data.
type TTags struct {
	g.Meta    `orm:"table:t_tags, do:true"`
	Id        interface{} // 标签ID（微信生成）
	TagName   interface{} // 标签名称
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 修改时间
}
