// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserTagRelations is the golang structure of table t_user_tag_relations for DAO operations like Where/Data.
type UserTagRelations struct {
	g.Meta    `orm:"table:t_user_tag_relations, do:true"`
	Id        interface{} // 主键ID
	TagId     interface{} // 标签ID
	UserId    interface{} // 用户ID
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 修改时间
}
