// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SubscriptionPeriods is the golang structure for table subscription_periods.
type SubscriptionPeriods struct {
	Id               int         `json:"id"               ` //
	SubscriptionNo   string      `json:"subscriptionNo"   ` // 订阅单号
	Uid              int64       `json:"uid"              ` // 用户ID
	App              string      `json:"app"              ` // 应用标识
	Package          string      `json:"package"          ` // app包名称
	Channel          string      `json:"channel"          ` // 支付渠道
	Version          string      `json:"version"          ` // 订阅时app版本号
	Sku              string      `json:"sku"              ` // 商品ID
	PurchaseToken    string      `json:"purchaseToken"    ` // 用户订阅的token
	TransactionNo    string      `json:"transactionNo"    ` // 续订交易号
	Amount           uint        `json:"amount"           ` // 订单金额
	CreatedBy        string      `json:"createdBy"        ` // 创建资源的用户标识
	NotificationType int         `json:"notificationType" ` // 通知状态
	Type             int         `json:"type"             ` // 状态 1. 新订阅； 2.订阅成功续费 3. 订阅已过期； 4. 订阅已暂停； 5： 订阅已撤销
	Credential       string      `json:"credential"       ` // json交易凭证
	CreatedAt        *gtime.Time `json:"createdAt"        ` // 创建时间
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` // 更新时间
	DeletedAt        *gtime.Time `json:"deletedAt"        ` // 删除时间
	StartedAt        *gtime.Time `json:"startedAt"        ` // 订阅开始时间
	ExpiredAt        *gtime.Time `json:"expiredAt"        ` // 订阅到期时间
}
