// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SubscriptionCallbacks is the golang structure for table subscription_callbacks.
type SubscriptionCallbacks struct {
	Id                    int64       `json:"id"                    ` // 主键ID
	App                   string      `json:"app"                   ` // 应用标识
	SubscriptionNo        string      `json:"subscriptionNo"        ` // 订阅单号
	Channel               string      `json:"channel"               ` // 支付渠道
	OriginalTransactionId string      `json:"originalTransactionId" ` // 第三方原始交易号
	TransactionNo         string      `json:"transactionNo"         ` // 第三方交易号
	Type                  int         `json:"type"                  ` // 回调类型1=第三方回调2=内部回调
	Status                int         `json:"status"                ` // 当前回调的订阅状态
	Data                  string      `json:"data"                  ` // json回调数据
	Result                string      `json:"result"                ` // 回调结果
	CreatedAt             *gtime.Time `json:"createdAt"             ` // 创建时间
	UpdatedAt             *gtime.Time `json:"updatedAt"             ` // 更新时间
	DeletedAt             *gtime.Time `json:"deletedAt"             ` // 删除时间
}
