// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Subscriptions is the golang structure for table subscriptions.
type Subscriptions struct {
	Id                    int64       `json:"id"                    ` // 主键ID
	SubscriptionNo        string      `json:"subscriptionNo"        ` // 订阅单号
	Uid                   int64       `json:"uid"                   ` // 用户ID
	Sku                   string      `json:"sku"                   ` // 商品ID
	IsSandbox             int         `json:"isSandbox"             ` // 是否是沙盒环境
	App                   string      `json:"app"                   ` // 平台app名称
	Package               string      `json:"package"               ` // app包名称
	Channel               string      `json:"channel"               ` // 支付渠道
	PayConfig             string      `json:"payConfig"             ` // 生成时的支付配置信息
	SubscriptionId        string      `json:"subscriptionId"        ` // 订阅ID
	Amount                uint        `json:"amount"                ` // 订单金额
	PurchaseToken         string      `json:"purchaseToken"         ` // 用户订阅的最新的token
	Subject               string      `json:"subject"               ` // 商品标题
	Body                  string      `json:"body"                  ` // 商品描述
	Extra                 string      `json:"extra"                 ` // json支付额外数据
	OriginalTransactionId string      `json:"originalTransactionId" ` // 第三方原始交易号
	Credential            string      `json:"credential"            ` // json交易凭证
	Version               string      `json:"version"               ` // 订阅时app版本号
	Currency              string      `json:"currency"              ` //
	SubscriptionPeriod    int         `json:"subscriptionPeriod"    ` // 订阅周期（单位：天）
	Status                int         `json:"status"                ` // 状态 -1: 已过期； 0 待付款； 1 - 订阅中； 2 - 订阅已失效； 3 - 订阅已暂停； 4 - 订阅已撤销；
	CreatedBy             string      `json:"createdBy"             ` // 创建资源的用户标识
	CallbackUri           string      `json:"callbackUri"           ` // 回调地址
	CallbackResult        string      `json:"callbackResult"        ` // 回调结果
	Remark                string      `json:"remark"                ` // 备注
	PayAccount            string      `json:"payAccount"            ` // 支付账号
	Meta                  string      `json:"meta"                  ` // json自定义元数据
	ExpiredAt             *gtime.Time `json:"expiredAt"             ` // 过期时间
	RefundedAt            *gtime.Time `json:"refundedAt"            ` // 退款时间
	ReversedAt            *gtime.Time `json:"reversedAt"            ` // 撤销时间
	CreatedAt             *gtime.Time `json:"createdAt"             ` // 创建时间
	UpdatedAt             *gtime.Time `json:"updatedAt"             ` // 更新时间
	DeletedAt             *gtime.Time `json:"deletedAt"             ` // 删除时间
	StartedAt             *gtime.Time `json:"startedAt"             ` // 订阅开始时间
	EndedAt               *gtime.Time `json:"endedAt"               ` // 订阅到期时间
}
