// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id        int         `json:"id"        ` //
	OpenId    string      `json:"openId"    ` // 用户的标识，对当前公众号唯一
	Nikename  string      `json:"nikename"  ` // 用户名称
	Username  string      `json:"username"  ` // 用户名称
	Sex       int         `json:"sex"       ` // 性别； 0 - 未知；1 - 男 ；2 - 女
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 修改时间
}
