// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserTagRelations is the golang structure for table user_tag_relations.
type UserTagRelations struct {
	Id        int         `json:"id"        ` // 主键ID
	TagId     int64       `json:"tagId"     ` // 标签ID
	UserId    int         `json:"userId"    ` // 用户ID
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 修改时间
}
