// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SubscriptionCallbacksDao is the data access object for table subscription_callbacks.
type SubscriptionCallbacksDao struct {
	table   string                       // table is the underlying table name of the DAO.
	group   string                       // group is the database configuration group name of current DAO.
	columns SubscriptionCallbacksColumns // columns contains all the column names of Table for convenient usage.
}

// SubscriptionCallbacksColumns defines and stores column names for table subscription_callbacks.
type SubscriptionCallbacksColumns struct {
	Id                    string // 主键ID
	App                   string // 应用标识
	SubscriptionNo        string // 订阅单号
	Channel               string // 支付渠道
	OriginalTransactionId string // 第三方原始交易号
	TransactionNo         string // 第三方交易号
	Type                  string // 回调类型1=第三方回调2=内部回调
	Status                string // 当前回调的订阅状态
	Data                  string // json回调数据
	Result                string // 回调结果
	CreatedAt             string // 创建时间
	UpdatedAt             string // 更新时间
	DeletedAt             string // 删除时间
}

//  subscriptionCallbacksColumns holds the columns for table subscription_callbacks.
var subscriptionCallbacksColumns = SubscriptionCallbacksColumns{
	Id:                    "id",
	App:                   "app",
	SubscriptionNo:        "subscription_no",
	Channel:               "channel",
	OriginalTransactionId: "original_transaction_id",
	TransactionNo:         "transaction_no",
	Type:                  "type",
	Status:                "status",
	Data:                  "data",
	Result:                "result",
	CreatedAt:             "created_at",
	UpdatedAt:             "updated_at",
	DeletedAt:             "deleted_at",
}

// NewSubscriptionCallbacksDao creates and returns a new DAO object for table data access.
func NewSubscriptionCallbacksDao() *SubscriptionCallbacksDao {
	return &SubscriptionCallbacksDao{
		group:   "default",
		table:   "subscription_callbacks",
		columns: subscriptionCallbacksColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SubscriptionCallbacksDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SubscriptionCallbacksDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SubscriptionCallbacksDao) Columns() SubscriptionCallbacksColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SubscriptionCallbacksDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SubscriptionCallbacksDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SubscriptionCallbacksDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
