// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserTagRelationsDao is the data access object for table t_user_tag_relations.
type UserTagRelationsDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns UserTagRelationsColumns // columns contains all the column names of Table for convenient usage.
}

// UserTagRelationsColumns defines and stores column names for table t_user_tag_relations.
type UserTagRelationsColumns struct {
	Id        string // 主键ID
	TagId     string // 标签ID
	UserId    string // 用户ID
	CreatedAt string // 创建时间
	UpdatedAt string // 修改时间
}

//  userTagRelationsColumns holds the columns for table t_user_tag_relations.
var userTagRelationsColumns = UserTagRelationsColumns{
	Id:        "id",
	TagId:     "tag_id",
	UserId:    "user_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUserTagRelationsDao creates and returns a new DAO object for table data access.
func NewUserTagRelationsDao() *UserTagRelationsDao {
	return &UserTagRelationsDao{
		group:   "default",
		table:   "t_user_tag_relations",
		columns: userTagRelationsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserTagRelationsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserTagRelationsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserTagRelationsDao) Columns() UserTagRelationsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserTagRelationsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserTagRelationsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserTagRelationsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
